/* Route */
export const ROUTE_PATH = {
  INDEX: "/",
  PRODUCT: "/products",
  PRODUCT_MOUSE: "/products/mouse",
  PRODUCT_KEYBOARD: "/products/keyboard",
  PRODUCT_HEADSET: "/products/headset",
  PRODUCT_FANS_COOLERS: "/products/fans-and-coolers",
  PRODUCT_PCCASE: "/products/pc-case",
  PRODUCT_PSU: "/products/psu",
  PRODUCT_ACCESSORIES: "/products/accessories",
  SUPPORT: "/support",
  SUPPORT_BROCHURE_MANUALS: "/support/brochures-and-manuals",
  SUPPORT_DRIVERS_SOFTWARES: "/support/drivers-and-softwares",
  SHOP: "/shop",
  CONTACT: "/contact",
  CONTACT_INQUIRY: "/contact/inquiry",
  CONTACT_BECOME_DISTRIBUTOR: "/contact/become-a-distributor",
  PRODUCT_DETAIL: "/products/:productID",
  PRODUCT_CATEGORY: "/products/:categoryID",
  BECOME_DISTRIBUTOR: "/become-distributor",
};
